#logging:
#  #日志存储地址
#  file: "logs/config/demo-xx.log"
#info:
#  name : "入门案例"

server:
  #端口号
  port: 8888
  #项目名，如果不设定，默认是 /
#  context-path: /demo
wechat:
  #微信开发者ID
  mpAppId: wxcb6afee676d68aa8
  #微信开发者密码
  mpAppSecret: 38cf957a98a2ac009a2b2840e74fd52f
