export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';

export const CHANGE_USER_TYPE = 'CHANGE_USER_TYPE';
export const CHANGE_USER_TYPE_TO_PROFILED = 'CHANGE_USER_TYPE_TO_PROFILED';
export const CHANGE_USER_PROFILE = 'CHANGE_USER_PROFILE';
export const CHANGE_MATCHER_PROFILE = 'CHANGE_MATCHER_PROFILE';
export const GET_MATCHER_PROFILE = 'GET_MATCHER_PROFILE';


export const INCREMENT = 'increment';
export const DECREMENT = 'decrement';
